CREATE TABLE product (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  name VARCHAR2(255),
  description VARCHAR2(255),
  launch_date DATE,
  interest_count NUMBER,
  is_trendy BOOLEAN
);

CREATE TABLE inventory (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  product_id NUMBER,
  stock_quantity NUMBER,
  stock_date DATE,
  FOREIGN KEY (product_id) REFERENCES product(id)
);

CREATE TABLE restock_notification (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  product_id NUMBER,
  notified BOOLEAN,
  FOREIGN KEY (product_id) REFERENCES product(id)
);
